# Generated by Django 6.0.2 on 2026-03-06 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_candidat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidat',
            options={'ordering': ['-created_at'], 'verbose_name': 'Candidat', 'verbose_name_plural': 'Candidats'},
        ),
        migrations.AddField(
            model_name='candidat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='antenne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats', to='Base.centre'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats_crees', to=settings.AUTH_USER_MODEL),
        ),
    ]
