# Generated by Django 6.0.2 on 2026-03-07 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_alter_candidat_options_candidat_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_formation', models.CharField(max_length=200)),
                ('organisme_formation', models.CharField(max_length=200)),
                ('nom_formateur', models.CharField(max_length=200)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('type_formation', models.CharField(choices=[('continue', 'Formation Continue'), ('apprentissage', 'Apprentissage')], max_length=20)),
                ('entreprise_formation', models.CharField(blank=True, help_text='Obligatoire pour une formation continue', max_length=200, null=True)),
                ('antenne', models.CharField(choices=[('conakry', 'Conakry'), ('forecariah', 'Forecariah'), ('boke', 'Boké'), ('kindia', 'Kindia'), ('labe', 'Labé'), ('mamou', 'Mamou'), ('faranah', 'Faranah'), ('kankan', 'Kankan'), ('siguiri', 'Siguiri'), ('nzerekore', "N'Zérékoré")], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='candidat',
            name='formation',
            field=models.ForeignKey(blank=True, help_text='Formation ONFPP à laquelle le candidat est inscrit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats', to='Base.formation'),
        ),
    ]
