# Generated by Django 6.0.2 on 2026-03-07 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0006_formation_candidat_formation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='metier_souhaite',
        ),
        migrations.AddField(
            model_name='candidat',
            name='antenne_code',
            field=models.CharField(blank=True, choices=[('conakry', 'Conakry'), ('forecariah', 'Forecariah'), ('boke', 'Boké'), ('kindia', 'Kindia'), ('labe', 'Labé'), ('mamou', 'Mamou'), ('faranah', 'Faranah'), ('kankan', 'Kankan'), ('siguiri', 'Siguiri'), ('nzerekore', "N'Zérékoré")], help_text="Code antenne si la FK Centre n'est pas utilisée", max_length=50, null=True, verbose_name='Antenne (code)'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='conseiller',
            field=models.CharField(blank=True, help_text='Nom du conseiller ou agent ayant traité le dossier', max_length=150, null=True, verbose_name='Conseiller responsable'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='domaine',
            field=models.CharField(blank=True, choices=[('informatique', 'Informatique & Numérique'), ('electrotechnique', 'Électrotechnique'), ('btp', 'Bâtiment & Travaux Publics'), ('mecanique', 'Mécanique & Auto'), ('agriculture', 'Agriculture & Élevage'), ('commerce', 'Commerce & Gestion'), ('sante', 'Santé & Social'), ('couture', 'Couture & Textile'), ('hotellerie', 'Hôtellerie & Restauration'), ('artisanat', 'Artisanat'), ('energie', 'Énergie solaire'), ('transport', 'Transport & Logistique'), ('peche', 'Pêche & Aquaculture'), ('autre', 'Autre')], help_text="Domaine de compétences ou d'intérêt du candidat", max_length=30, null=True, verbose_name='Domaine'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='formation_ciblee',
            field=models.CharField(blank=True, help_text='Intitulé libre de la formation souhaitée par le candidat', max_length=200, null=True, verbose_name='Formation ciblée'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='metier_actuel',
            field=models.CharField(blank=True, help_text="Métier exercé au moment de l'inscription", max_length=150, null=True, verbose_name='Métier actuel'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='motivation',
            field=models.TextField(blank=True, help_text='Motivation du candidat pour la formation', null=True, verbose_name='Motivation'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='observation',
            field=models.TextField(blank=True, help_text="Remarques du conseiller ou de l'agent d'inscription", null=True, verbose_name='Observation'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='situation',
            field=models.CharField(blank=True, choices=[('chomeur', 'Chômeur(se)'), ('actif', 'Actif(ve)'), ('diplome', 'Diplômé(e) sans emploi'), ('etudiant', 'Étudiant(e)'), ('reconversion', 'En reconversion professionnelle'), ('independant', 'Travailleur indépendant'), ('autre', 'Autre')], max_length=20, null=True, verbose_name='Situation actuelle'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='adresse',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='antenne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats', to='Base.centre', verbose_name='Antenne (Centre)'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='formation',
            field=models.ForeignKey(blank=True, help_text='Formation ONFPP à laquelle le candidat est rattaché', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats', to='Base.formation', verbose_name='Session de formation'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='identifiant_unique',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Identifiant unique'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='niveau_etude',
            field=models.CharField(blank=True, choices=[('CEP', 'CEP'), ('BEPC', 'BEPC'), ('BAC', 'BAC'), ('BTS', 'BTS'), ('Licence', 'Licence'), ('Master', 'Master'), ('Doctorat', 'Doctorat'), ('sans_diplome', 'Sans diplôme'), ('autre', 'Autre')], max_length=20, null=True, verbose_name="Niveau d'étude"),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='prenom',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='sexe',
            field=models.CharField(blank=True, choices=[('H', 'Homme'), ('F', 'Femme')], max_length=10, null=True, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='statut_fiche',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='Statut de la fiche'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='antenne',
            field=models.CharField(choices=[('conakry', 'Conakry'), ('forecariah', 'Forecariah'), ('boke', 'Boké'), ('kindia', 'Kindia'), ('labe', 'Labé'), ('mamou', 'Mamou'), ('faranah', 'Faranah'), ('kankan', 'Kankan'), ('siguiri', 'Siguiri'), ('nzerekore', "N'Zérékoré")], max_length=50, verbose_name='Antenne ONFPP'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='entreprise_formation',
            field=models.CharField(blank=True, help_text='Obligatoire pour une formation continue (DFC)', max_length=200, null=True, verbose_name='Entreprise de formation'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='nom_formateur',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Formateur'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='nom_formation',
            field=models.CharField(max_length=200, verbose_name='Titre de la formation'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='organisme_formation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Organisme'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='type_formation',
            field=models.CharField(blank=True, choices=[('continue', 'Formation Continue'), ('apprentissage', 'Apprentissage')], max_length=20, null=True, verbose_name='Type de formation'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
    ]
