# Generated by Django 6.0.2 on 2026-03-07 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_remove_candidat_metier_souhaite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='antenne_code',
        ),
        migrations.AlterField(
            model_name='candidat',
            name='antenne',
            field=models.CharField(blank=True, choices=[('conakry', 'Conakry'), ('forecariah', 'Forecariah'), ('boke', 'Boké'), ('kindia', 'Kindia'), ('labe', 'Labé'), ('mamou', 'Mamou'), ('faranah', 'Faranah'), ('kankan', 'Kankan'), ('siguiri', 'Siguiri'), ('nzerekore', "N'Zérékoré")], help_text='Code antenne du candidat (conakry, kankan, labe…)', max_length=50, null=True, verbose_name='Antenne ONFPP'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='conseiller',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Conseiller responsable'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='domaine',
            field=models.CharField(blank=True, choices=[('informatique', 'Informatique & Numérique'), ('electrotechnique', 'Électrotechnique'), ('btp', 'Bâtiment & Travaux Publics'), ('mecanique', 'Mécanique & Auto'), ('agriculture', 'Agriculture & Élevage'), ('commerce', 'Commerce & Gestion'), ('sante', 'Santé & Social'), ('couture', 'Couture & Textile'), ('hotellerie', 'Hôtellerie & Restauration'), ('artisanat', 'Artisanat'), ('energie', 'Énergie solaire'), ('transport', 'Transport & Logistique'), ('peche', 'Pêche & Aquaculture'), ('autre', 'Autre')], max_length=30, null=True, verbose_name='Domaine'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats', to='Base.formation', verbose_name='Session de formation'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='formation_ciblee',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Formation ciblée'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='metier_actuel',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Métier actuel'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='motivation',
            field=models.TextField(blank=True, null=True, verbose_name='Motivation'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observation'),
        ),
    ]
