# Generated by Django 6.0.2 on 2026-03-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0008_remove_candidat_antenne_code_alter_candidat_antenne_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidat',
            options={'ordering': ['-created_at'], 'verbose_name': 'Candidat / Apprenant', 'verbose_name_plural': 'Candidats / Apprenants'},
        ),
        migrations.AddField(
            model_name='candidat',
            name='commentaire_insertion',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire insertion (conseiller)'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='date_insertion',
            field=models.DateField(blank=True, null=True, verbose_name='Date de prise de poste'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='date_suivi_insertion',
            field=models.DateField(blank=True, null=True, verbose_name='Date du dernier suivi insertion'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='duree_recherche_emploi',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Nombre de mois entre la fin de la formation et l'obtention du poste", null=True, verbose_name="Durée de recherche d'emploi (mois)"),
        ),
        migrations.AddField(
            model_name='candidat',
            name='entreprise_insertion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Entreprise d'insertion"),
        ),
        migrations.AddField(
            model_name='candidat',
            name='formation_complementaire',
            field=models.BooleanField(blank=True, help_text="L'apprenant a-t-il suivi une autre formation après l'ONFPP ?", null=True, verbose_name='Formation complémentaire suivie'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='insere',
            field=models.BooleanField(blank=True, help_text='True = apprenant inséré dans une entreprise après la formation', null=True, verbose_name='Inséré en entreprise'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='poste_occupe',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Poste / Intitulé du métier occupé'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='salaire_insertion',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Salaire mensuel brut (GNF)'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='satisfaction_formation',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 — Très insatisfait'), (2, '2 — Insatisfait'), (3, '3 — Neutre'), (4, '4 — Satisfait'), (5, '5 — Très satisfait')], null=True, verbose_name='Satisfaction formation (1-5)'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='secteur_activite',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Secteur d'activité de l'entreprise"),
        ),
        migrations.AddField(
            model_name='candidat',
            name='statut_emploi_actuel',
            field=models.CharField(blank=True, choices=[('en_poste', 'En poste'), ('chomage', 'Au chômage'), ('independant', 'Indépendant / Auto-entrepreneur'), ('etudes', "Poursuite d'études"), ('autre', 'Autre')], max_length=20, null=True, verbose_name='Statut emploi actuel'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='suivi_par',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Suivi insertion par'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='type_contrat',
            field=models.CharField(blank=True, choices=[('cdi', 'CDI — Contrat à durée indéterminée'), ('cdd', 'CDD — Contrat à durée déterminée'), ('stage', 'Stage / Apprentissage'), ('freelance', 'Freelance / Auto-entrepreneur'), ('informel', 'Emploi informel'), ('sans', 'Sans contrat formalisé')], max_length=20, null=True, verbose_name='Type de contrat'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='antenne',
            field=models.CharField(blank=True, choices=[('conakry', 'Conakry'), ('forecariah', 'Forecariah'), ('boke', 'Boké'), ('kindia', 'Kindia'), ('labe', 'Labé'), ('mamou', 'Mamou'), ('faranah', 'Faranah'), ('kankan', 'Kankan'), ('siguiri', 'Siguiri'), ('nzerekore', "N'Zérékoré")], max_length=50, null=True, verbose_name='Antenne ONFPP'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='domaine',
            field=models.CharField(blank=True, choices=[('informatique', 'Informatique & Numérique'), ('electrotechnique', 'Électrotechnique'), ('btp', 'Bâtiment & Travaux Publics'), ('mecanique', 'Mécanique & Auto'), ('agriculture', 'Agriculture & Élevage'), ('commerce', 'Commerce & Gestion'), ('sante', 'Santé & Social'), ('couture', 'Couture & Textile'), ('hotellerie', 'Hôtellerie & Restauration'), ('artisanat', 'Artisanat'), ('energie', 'Énergie solaire'), ('transport', 'Transport & Logistique'), ('peche', 'Pêche & Aquaculture'), ('autre', 'Autre')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='metier_actuel',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Métier avant formation'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='niveau_etude',
            field=models.CharField(blank=True, choices=[('CEP', 'CEP'), ('BEPC', 'BEPC'), ('BAC', 'BAC'), ('BTS', 'BTS'), ('Licence', 'Licence'), ('Master', 'Master'), ('Doctorat', 'Doctorat'), ('sans_diplome', 'Sans diplôme'), ('autre', 'Autre')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='sexe',
            field=models.CharField(blank=True, choices=[('H', 'Homme'), ('F', 'Femme')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='situation',
            field=models.CharField(blank=True, choices=[('chomeur', 'Chômeur(se)'), ('actif', 'Actif(ve)'), ('diplome', 'Diplômé(e) sans emploi'), ('etudiant', 'Étudiant(e)'), ('reconversion', 'En reconversion professionnelle'), ('independant', 'Travailleur indépendant'), ('autre', 'Autre')], max_length=20, null=True, verbose_name='Situation avant formation'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
