# Generated by Django 6.0.2 on 2026-03-08 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0009_alter_candidat_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepriseFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_unique', models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='Identifiant unique')),
                ('nom_entreprise', models.CharField(max_length=255, verbose_name="Nom de l'entreprise")),
                ('secteur_activite', models.CharField(blank=True, max_length=200, null=True, verbose_name="Secteur d'activité")),
                ('adresse_entreprise', models.TextField(blank=True, null=True, verbose_name="Adresse de l'entreprise")),
                ('contact_rh', models.CharField(blank=True, max_length=150, null=True, verbose_name='Contact RH / Responsable formation')),
                ('telephone_entreprise', models.CharField(blank=True, max_length=30, null=True)),
                ('email_entreprise', models.EmailField(blank=True, max_length=254, null=True)),
                ('intitule_formation', models.CharField(max_length=255, verbose_name='Intitulé de la formation')),
                ('objectifs', models.TextField(blank=True, null=True, verbose_name='Objectifs de la formation')),
                ('antenne', models.CharField(choices=[('conakry', 'Conakry'), ('forecariah', 'Forecariah'), ('boke', 'Boké'), ('kindia', 'Kindia'), ('labe', 'Labé'), ('mamou', 'Mamou'), ('faranah', 'Faranah'), ('kankan', 'Kankan'), ('siguiri', 'Siguiri'), ('nzerekore', "N'Zérékoré")], max_length=50, verbose_name='Antenne ONFPP')),
                ('nb_hommes', models.PositiveIntegerField(default=0, verbose_name="Nombre d'hommes")),
                ('nb_femmes', models.PositiveIntegerField(default=0, verbose_name='Nombre de femmes')),
                ('date_soumission', models.DateField(auto_now_add=True, verbose_name='Date de soumission')),
                ('date_debut_prevue', models.DateField(blank=True, null=True, verbose_name='Date de début prévue')),
                ('date_fin_prevue', models.DateField(blank=True, null=True, verbose_name='Date de fin prévue')),
                ('date_realisation', models.DateField(blank=True, null=True, verbose_name='Date de réalisation effective')),
                ('statut_realisation', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours de traitement'), ('realisee', 'Réalisée'), ('annulee', 'Annulée'), ('reportee', 'Reportée')], default='planifiee', max_length=20, verbose_name='Statut de réalisation')),
                ('plan_formation_fichier', models.FileField(blank=True, help_text='PDF, Word, Excel acceptés', null=True, upload_to='plans_formation/', verbose_name='Plan de formation (fichier)')),
                ('plan_formation_url', models.URLField(blank=True, null=True, verbose_name='Lien vers le plan de formation')),
                ('plan_formation_nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du fichier plan de formation')),
                ('nb_formes_hommes', models.PositiveIntegerField(default=0, verbose_name="Nombre d'hommes formés (réalisé)")),
                ('nb_formes_femmes', models.PositiveIntegerField(default=0, verbose_name='Nombre de femmes formées (réalisé)')),
                ('rapport_final', models.TextField(blank=True, null=True, verbose_name='Rapport / Observations finales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entreprise_formations_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('session_evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entreprise_formations', to='Base.evaluationsession', verbose_name="Session d'évaluation liée")),
            ],
            options={
                'verbose_name': 'Plan de formation entreprise (DFC)',
                'verbose_name_plural': 'Plans de formation entreprises (DFC)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModulePlanFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule_module', models.CharField(max_length=255, verbose_name='Intitulé du module')),
                ('contenu', models.TextField(blank=True, null=True, verbose_name='Contenu / Programme')),
                ('duree_heures', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Durée (heures)')),
                ('formateur', models.CharField(blank=True, max_length=200, null=True, verbose_name='Formateur prévu')),
                ('lieu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lieu de formation')),
                ('date_debut_prevue', models.DateField(blank=True, null=True, verbose_name='Début prévu')),
                ('date_fin_prevue', models.DateField(blank=True, null=True, verbose_name='Fin prévue')),
                ('date_realisation', models.DateField(blank=True, null=True, verbose_name='Date de réalisation')),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours de traitement'), ('realisee', 'Réalisée'), ('annulee', 'Annulée'), ('reportee', 'Reportée')], default='planifiee', max_length=20, verbose_name='Statut')),
                ('nb_hommes_module', models.PositiveSmallIntegerField(default=0, verbose_name='Hommes (module)')),
                ('nb_femmes_module', models.PositiveSmallIntegerField(default=0, verbose_name='Femmes (module)')),
                ('observations', models.TextField(blank=True, null=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('entreprise_formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='Base.entrepriseformation', verbose_name='Plan de formation')),
            ],
            options={
                'verbose_name': 'Module du plan de formation',
                'verbose_name_plural': 'Modules du plan de formation',
                'ordering': ['ordre', 'date_debut_prevue'],
            },
        ),
    ]
