# Generated by Django 6.0.2 on 2026-03-08 11:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0010_entrepriseformation_moduleplanformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_unique', models.CharField(blank=True, max_length=30, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='formateurs/photos/')),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.CharField(blank=True, max_length=250, null=True)),
                ('antenne', models.CharField(blank=True, choices=[('conakry', 'Conakry'), ('forecariah', 'Forecariah'), ('boke', 'Boké'), ('kindia', 'Kindia'), ('labe', 'Labé'), ('mamou', 'Mamou'), ('faranah', 'Faranah'), ('kankan', 'Kankan'), ('siguiri', 'Siguiri'), ('nzerekore', "N'Zérékoré")], max_length=20, null=True)),
                ('type', models.CharField(choices=[('individuel', 'Formateur individuel'), ('organisme', 'Organisme / Cabinet de formation')], default='individuel', max_length=15)),
                ('nom_cabinet', models.CharField(blank=True, help_text='Nom du cabinet si organisme', max_length=200, null=True)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('domaine', models.CharField(blank=True, choices=[('btp', 'BTP — Bâtiment & Travaux Publics'), ('agriculture', 'Agriculture & Élevage'), ('numerique', 'Numérique & Technologies'), ('sante', 'Santé & Social'), ('commerce', 'Commerce & Gestion'), ('artisanat', 'Artisanat & Textile'), ('tourisme', 'Tourisme & Hôtellerie'), ('autres', 'Autre domaine')], max_length=20, null=True)),
                ('specialite', models.CharField(blank=True, help_text='Métier choisi dans la liste du domaine', max_length=150, null=True)),
                ('domaine_autre', models.CharField(blank=True, help_text="Saisie libre si domaine = 'autres'", max_length=150, null=True)),
                ('experience_annees', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diplome', models.CharField(blank=True, max_length=200, null=True)),
                ('certifications', models.CharField(blank=True, max_length=300, null=True)),
                ('langues', models.CharField(blank=True, max_length=150, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('note_manuelle', models.FloatField(blank=True, help_text='Note 0-5 saisie manuellement', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('note_evaluation', models.FloatField(blank=True, help_text='Moyenne calculée depuis les évaluations de sessions', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('nb_evaluations', models.PositiveIntegerField(default=0, help_text="Nombre d'évaluations de sessions ayant alimenté note_evaluation")),
                ('detail_evaluation', models.JSONField(blank=True, help_text='Détail note par critère {critere: moyenne}', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formateurs_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formateur',
                'verbose_name_plural': 'Formateurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
