# Generated by Django 6.0.2 on 2026-03-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0011_formateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateur',
            name='types_formation',
            field=models.JSONField(default=list, help_text="Liste: 'continue' (DFC) et/ou 'apprentissage' (DAP)"),
        ),
    ]
