# Generated by Django 6.0.2 on 2026-03-08 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0012_formateur_types_formation'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationsession',
            name='formateur_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_evaluation', to='Base.formateur', verbose_name='Formateur (référence)'),
        ),
    ]
