# Generated by Django 6.0.2 on 2026-03-08 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0013_evaluationsession_formateur_ref'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Identifiant technique : ex 'formations_dap'", max_length=80, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('niveau_min', models.IntegerField(default=30)),
                ('divisions', models.CharField(blank=True, help_text='Codes séparés par virgule ex: DAP,DFC — vide = toutes', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Page disponible globalement sur la plateforme')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['-level']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AddField(
            model_name='user',
            name='antenne',
            field=models.CharField(blank=True, choices=[('conakry', 'Conakry'), ('forecariah', 'Forecariah'), ('boke', 'Boké'), ('kindia', 'Kindia'), ('labe', 'Labé'), ('mamou', 'Mamou'), ('faranah', 'Faranah'), ('kankan', 'Kankan'), ('siguiri', 'Siguiri'), ('nzerekore', "N'Zérékoré")], help_text="Obligatoire pour Chef d'Antenne", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='division',
            field=models.CharField(blank=True, choices=[('DAP', 'Division Apprentissage et Projets Collectifs'), ('DSE', 'Division Suivi Évaluation'), ('DFC', 'Division Formation Continue'), ('DPL', 'Division Planification')], help_text='Obligatoire pour Chef de Division, Chef de Section, Conseiller', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='level',
            field=models.IntegerField(default=1, help_text='100=DG · 90=DGA · 70=Chef Div · 60=Chef Section · 50=Chef Antenne · 30=Conseiller'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Base.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_permissions_set', to='auth.permission'),
        ),
        migrations.CreateModel(
            name='UserPageAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allowed', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='Base.page')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_access_updates', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'page__key'],
                'unique_together': {('user', 'page')},
            },
        ),
    ]
