# Generated by Django 6.0.2 on 2026-03-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0014_page_alter_role_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
