# Generated by Django 6.0.2 on 2026-03-10 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0015_alter_region_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='antenne',
            new_name='antenne_onfpp',
        ),
    ]
