# Generated by Django 6.0.2 on 2026-03-11 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0016_rename_antenne_user_antenne_onfpp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='antenne_onfpp',
            new_name='antenne',
        ),
    ]
